### ISSUE TITLE
errors happend when checkout elastix through svn

### ISSUE THREAD

**Issue by vinllen** [kaspermarstal/SimpleElastix#25]
Hi, When i make the project SimpleElastix, errors occured when downloading elastix:

```
vinllen@ ~/opt/elastix/build_SimpleElastix$ make -j4
[ 16%] Built target PCRE
[ 32%] Built target ITK
[ 48%] Built target Swig
[ 51%] Performing download step (SVN checkout) for 'elastix'
svn: E175002: Unable to connect to a repository at URL 'https://svn.bigr.nl/elastix/trunkpublic'
svn: E175002: OPTIONS of 'https://svn.bigr.nl/elastix/trunkpublic': SSL handshake failed: Secure connection truncated (https://svn.bigr.nl)
make[2]: *** [elastix-prefix/src/elastix-stamp/elastix-download] Error 1
make[1]: *** [CMakeFiles/elastix.dir/all] Error 2
make: *** [all] Error 2
```

I found the solution list in the TroubleShooting in the [Getting Started](http://simpleelastix.readthedocs.org/GettingStarted.html#the-superbuild-throws-server-ssl-certificate-verification-failed-certificate-has-expired-during-checkout-of-elastix). But it looks like this solution not works for me.
My computer is MacOS, do you have any idea ? Thankyou very much

**Comment by kaspermarstal** [comment]
Hi, try again with a fresh clone. Let me know if the problem persists.

**Comment by vinllen** [comment]
Hi, Thanks Kaspermarstal. It works ok when the svn change a fresh clone.
But i have another error about the make the SimpleITK, there are too many outputs so i just copy part of it:
```
vinllen@ ~/opt/elastix/build_SimpleElastix$ make -j4
[ 16%] Built target ITK
[ 32%] Built target PCRE
[ 48%] Built target Swig
[ 65%] Built target elastix
[ 67%] Performing forcebuild step for 'SimpleITK'
[ 69%] Performing build step for 'SimpleITK'
[  0%] Built target gtest
[  1%] Built target lua5
[  9%] Built target SimpleITKData
[  9%] Built target lua
...
[ 61%] Building CXX object Testing/Unit/CMakeFiles/SimpleITKUnitTestDriver6.dir/sitkTernaryMagnitudeSquaredImageFilterTest.cxx.o
[ 61%] Building CXX object Testing/Unit/CMakeFiles/SimpleITKUnitTestDriver6.dir/sitkThresholdImageFilterTest.cxx.o
[ 62%] Linking CXX executable ../../bin/sitkTransformCompareDriver
[ 62%] Building CXX object Testing/Unit/CMakeFiles/SimpleITKUnitTestDriver6.dir/sitkThresholdMaximumConnectedComponentsImageFilterTest.cxx.o
[ 62%] Built target sitkTransformCompareDriver
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/AbsImageFilter.java:90: 错误: 缺少分号
Image itk::simple::AbsImageFilter::Execute(const Image &image1)
                                                       ^
[ 62%] Building CXX object Testing/Unit/CMakeFiles/SimpleITKUnitTestDriver6.dir/sitkThresholdSegmentationLevelSetImageFilterTest.cxx.o
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/AbsImageFilter.java:95: 警告: image1没有 @param
public  Image execute(Image image1) {
              ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/AbsImageFilter.java:95: 警告: 没有 @return
public  Image execute(Image image1) {
              ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/ProcessObject.java:56: 警告: 没有 @return
public  String getName() {
               ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/ProcessObject.java:141: 错误: 缺少分号
virtual int itk::simple::ProcessObject::AddCommand(itk::simple::EventEnum event, itk::simple::Command &cmd)
                                                                                                      ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/ProcessObject.java:168: 警告: event没有 @param
public  int addCommand(EventEnum event, Command cmd) {
            ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/ProcessObject.java:168: 警告: cmd没有 @param
public  int addCommand(EventEnum event, Command cmd) {
            ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/ProcessObject.java:168: 警告: 没有 @return
public  int addCommand(EventEnum event, Command cmd) {
            ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/ProcessObject.java:192: 警告: event没有 @param
public  boolean hasCommand(EventEnum event) {
                ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/ProcessObject.java:192: 警告: 没有 @return
public  boolean hasCommand(EventEnum event) {
                ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/ProcessObject.java:210: 警告: 没有 @return
public  float getProgress() {
              ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/AbsoluteValueDifferenceImageFilter.java:113: 错误: 缺少分号
Image itk::simple::AbsoluteValueDifferenceImageFilter::Execute(double constant, const Image &image2)
                                                                                            ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/AbsoluteValueDifferenceImageFilter.java:115: 警告: image1没有 @param
public  Image execute(Image image1, Image image2) {
              ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/AbsoluteValueDifferenceImageFilter.java:115: 警告: image2没有 @param
public  Image execute(Image image1, Image image2) {
              ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/AbsoluteValueDifferenceImageFilter.java:115: 警告: 没有 @return
public  Image execute(Image image1, Image image2) {
              ^
/Users/vinllen/opt/elastix/build_SimpleElastix/SimpleITK-build/Wrapping/org/itk/simple/AbsoluteValueDifferenceImageFilter.java:120: 错误: 缺少分号
Image itk::simple::AbsoluteValueDifferenceImageFilter::Execute(double constant, const Image &image2)
...
[ 63%] Building CXX object Testing/Unit/CMakeFiles/SimpleITKUnitTestDriver6.dir/sitkZeroCrossingBasedEdgeDetectionImageFilterTest.cxx.o
[ 63%] Building CXX object Testing/Unit/CMakeFiles/SimpleITKUnitTestDriver6.dir/sitkZeroCrossingImageFilterTest.cxx.o
[ 63%] Building CXX object Testing/Unit/CMakeFiles/SimpleITKUnitTestDriver6.dir/sitkZeroFluxNeumannPadImageFilterTest.cxx.o
[ 63%] Linking CXX executable ../../bin/SimpleITKUnitTestDriver6
[ 63%] Built target SimpleITKUnitTestDriver6
100 个错误
100 个警告
make[5]: *** [Wrapping/simpleitk-0.9.1.dev21-g47eb3.jar] Error 1
make[5]: *** Deleting file `Wrapping/simpleitk-0.9.1.dev21-g47eb3.jar'
make[4]: *** [Wrapping/CMakeFiles/org_itk_simple_jar.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
```
It looks like the errors happen when compiling jar package. Do you have any idea? Thankyou verymuch

**Comment by kaspermarstal** [comment]
Yes, this is a known problem with the SimpleITK java build. We have to wait for the next SimpleITK release for this problem be fixed. For now, just disable the java wrapping by setting the WRAP_JAVA CMake variable to OFF and the build will continue. If you need the Java wrapping, [this commit] shows how SimpleITK build was fixed and perhaps you can modify the SimpleElastix build locally.

**Comment by vinllen** [comment]
Which commit ? I just want to use the SimpleITK python package.
Thanks Kaspermarstal !

**Comment by kaspermarstal** [comment]
Oh, I meant [this commit](https://github.com/SimpleITK/SimpleITK/commit/b79ed010b6638678615fd5a9ddf1ff8d75c57cc6) but if you just need the Python package disregard these changes and just disable the Java build :blush:

**Comment by vinllen** [comment]
Hi, Kaspermarstal,
Thanks for your patient reply. As your suggestion, i disable the WRAP_JAVA and enable WRAP_PYTHON in the ccmake:
```
vinllen@ ~/opt/elastix/build_SimpleElastix/SimpleITK-build$ ccmake ..
```
When i configure it, the error shows that my python version is unsuitable:
```
 CMake Error at /usr/local/Cellar/cmake/3.3.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
   Could NOT find PythonLibs: Found unsuitable version "2.7.6", but required
   is exact version "2.7.10" (found /usr/lib/libpython2.7.dylib)
 Call Stack (most recent call first):
   /usr/local/Cellar/cmake/3.3.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
   /usr/local/Cellar/cmake/3.3.1/share/cmake/Modules/FindPythonLibs.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
   /Users/vinllen/opt/elastix/SimpleElastix/CMake/sitkLanguageOptions.cmake:38 (find_package)
   SuperBuild.cmake:244 (include)
   CMakeLists.txt:26 (include)
```
In my computer, i use `pyenv` to switch python version. Same error still exist even if i switch python to "2.7.10". When i switch python version to "3.4.0", the required version of python also switch to "3.4":
```
 CMake Error at /usr/local/Cellar/cmake/3.3.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
   Could NOT find PythonLibs: Found unsuitable version "2.7.6", but required
   is exact version "3.4" (found /usr/lib/libpython2.7.dylib)
 Call Stack (most recent call first):
   /usr/local/Cellar/cmake/3.3.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
   /usr/local/Cellar/cmake/3.3.1/share/cmake/Modules/FindPythonLibs.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
   /Users/vinllen/opt/elastix/SimpleElastix/CMake/sitkLanguageOptions.cmake:38 (find_package)
   SuperBuild.cmake:244 (include)
   CMakeLists.txt:26 (include)
```
I have tried to search some solutions to solve this problem, but still confused.

**Comment by PertuyF** [comment]
Hi vinllen,

If I remember well you can choose a python lib when configuring CMake with SimpleElastix SuperBuild. I would say that Cmake uses 2.7.6 lib by default and that you have to change it 2.7.10 or 3.4 lib depending on which Python version you want to use.

You should find the variables under "PYTHON" is you check "Grouped" and "Advanced" options in Cmake-gui.

Hope it helps

**Comment by vinllen** [comment]
I solved this problem by upgrading cmake version from 3.3 to 3.5.
So this problem can be closed.
Thankyou

**Comment by vinllen** [comment]
I think this [post](http://vinllen.com/switch-python-version-and-solve-this-problemfatal-python-error-pythreadstate_get-no-current-thread/) can help people who meet the same error in the building

**Comment by kaspermarstal** [comment]
Great, thanks for sharing!
